# Generated by Django 5.0.4 on 2024-04-28 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='icon/'),
        ),
        migrations.AddField(
            model_name='service',
            name='icon2',
            field=models.ImageField(blank=True, null=True, upload_to='icon2/'),
        ),
        migrations.AlterField(
            model_name='servicetitle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/'),
        ),
    ]
